name: action

on:
  push:
    paths:
      - '**/workflows/*.yml'
      - '**.cs'
      - '**.csproj'

jobs:
  build-and-test:
    
    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION: '8.x'
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        id: stepid
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - run: dotnet restore --locked-mode

      - run: dotnet build --configuration Release --no-restore

      - run: dotnet test --no-restore --verbosity normal
