name: action

on:
  push:
    paths:
      - '**/workflows/*.yml'
      - '**.cs'
      - '**.csproj'

env:
  DOTNET_VERSION: '8.x'
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        id: stepid
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true
          cache-dependency-path: '**/packages.lock.json'
      - run: dotnet restore --locked-mode
      - run: |
          ls
          cd src/Blank.Presentation
          dotnet build --configuration Release --no-restore
      - run: |
          ls
          cd tests
          dotnet test
