name: deploy release

on:
  push:
    branches:
      - 'release/**'

jobs:
  build-and-run-docker-image:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          # Build Docker image
          DOCKER_IMAGE_NAME=$GITHUB_REPOSITORY-lt:latest
          docker build --platform linux/amd64 --tag $DOCKER_IMAGE_NAME .

      - name: Run Docker image
        run: |
          # Run Docker image
          DOCKER_IMAGE_NAME=$GITHUB_REPOSITORY-lt:latest
          DOCKER_CONTAINER_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          docker stop $DOCKER_CONTAINER_NAME
          docker rm $DOCKER_CONTAINER_NAME
          docker run --detach \
            --name $DOCKER_CONTAINER_NAME \
            --env ASPNETCORE_ENVIRONMENT=Production \
            --env ASPNETCORE_HTTP_PORTS=${{ secrets.PRODUCTION_LT_APP_PORT }} \
          $DOCKER_IMAGE_NAME

      - name: Run Load test
        run: |
          # Run Load test
          mkdir report_$GITHUB_RUN_ID

      - name: Remove Docker image
        run: |
          # Remove Docker image
          DOCKER_IMAGE_NAME=$GITHUB_REPOSITORY-lt:latest
          DOCKER_CONTAINER_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          docker stop $DOCKER_CONTAINER_NAME
          docker rm $DOCKER_CONTAINER_NAME
          docker image remove $$DOCKER_IMAGE_NAME
