name: deploy release

on:
  push:
    branches:
      - 'release/**'

jobs:
  build-and-run-docker-image:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set GitHub Environment variables
        run: |
          # Set GitHub Environment variables
          echo "DOCKER_IMAGE_NAME=${GITHUB_REPOSITORY}-lt:latest" >> $GITHUB_ENV
          echo "DOCKER_CONTAINER_NAME=$(echo ${GITHUB_REPOSITORY} | cut -d'/' -f2)-lt" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          # Build Docker image
          docker build --platform linux/amd64 --tag ${{ env.DOCKER_IMAGE_NAME }} .

      - name: Run Docker image
        run: |
          # Run Docker image
          docker rm -f ${{ env.DOCKER_CONTAINER_NAME }}
          docker run --detach --rm \
            --name ${{ env.DOCKER_CONTAINER_NAME }} \
            --network k6-network \
            --env ASPNETCORE_ENVIRONMENT=Production \
            --env ASPNETCORE_HTTP_PORTS=${{ secrets.PRODUCTION_APP_PORT }} \
          ${{ env.DOCKER_IMAGE_NAME }}

      - name: Run Load test
        run: |
          # Run Load test
          cd k6 && mkdir report
          for script in *.scenario.js; do
            SCRIPT_NAME=$(echo $script | cut -d'/' -f2 | cut -d'.' -f1)
            docker run --rm \
              --name k6 \
              --publish 5665:5665 \
              --network k6-network \
              --user $(id -u):$(id -g) \
              --volume $(pwd):/k6 \
              --workdir /k6 \
              --env K6_WEB_DASHBOARD=true \
              --env K6_WEB_DASHBOARD_EXPORT=report/${SCRIPT_NAME}.report.html \
              --env APP_BASE_ADDRESS=http://${{ env.DOCKER_CONTAINER_NAME }}:${{ secrets.PRODUCTION_APP_PORT }} \
            grafana/k6:latest run $script
          done
          PUSHGATEWAY_BASE_ADDRESS=${{ secrets.PRODUCTION_PUSHGATEWAY_BASE_ADDRESS }} \
          JOB_NAME=k6 \
          INSTANCE_NAME=stg \
          python3 push_metrics.py

      - uses: actions/upload-artifact@v4
        with:
          name: report_${{ env.GITHUB_RUN_ID }}
          path: k6/report
          retention-days: 7

      - name: Remove Docker image
        run: |
          # Remove Docker image
          docker rm -f ${{ env.DOCKER_CONTAINER_NAME }}
          docker rmi -f ${{ env.DOCKER_IMAGE_NAME }}
