name: deploy release

on:
  push:
    branches:
      - 'release/**'

jobs:
  build-and-run-docker-image:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          # Build Docker image
          DOCKER_IMAGE_NAME=$GITHUB_REPOSITORY-lt:latest
          docker build --platform linux/amd64 --tag $DOCKER_IMAGE_NAME .

      - name: Run Docker image
        run: |
          # Run Docker image
          DOCKER_IMAGE_NAME=$GITHUB_REPOSITORY-lt:latest
          DOCKER_CONTAINER_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          docker rm -f $DOCKER_CONTAINER_NAME
          docker run --detach -rm \
            --name $DOCKER_CONTAINER_NAME \
            --env ASPNETCORE_ENVIRONMENT=Production \
            --env ASPNETCORE_HTTP_PORTS=${{ secrets.PRODUCTION_LT_APP_PORT }} \
          $DOCKER_IMAGE_NAME

      - name: Run Load test
        run: |
          # Run Load test
          for script in k6/*.js; do
            SCRIPT_NAME=$(echo $script | cut -d'/' -f2 | cut -d'.' -f1)
            docker run --rm \
              --name k6 \
              --volume $(pwd):/k6 \
              --env K6_WEB_DASHBOARD=true \
              --env K6_WEB_DASHBOARD_EXPORT=report_${GITHUB_RUN_ID}_${SCRIPT_NAME}.html \
              --env APP_PORT=${{ secrets.PRODUCTION_LT_APP_PORT }} \
            grafana/k6:latest run $script
          done

      - name: Remove Docker image
        run: |
          # Remove Docker image
          DOCKER_IMAGE_NAME=$GITHUB_REPOSITORY-lt:latest
          DOCKER_CONTAINER_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          docker rm -f $DOCKER_CONTAINER_NAME
          docker rmi $DOCKER_IMAGE_NAME
