name: staging

on:
  push:
    branches:
      - 'release/**'

jobs:
  build-and-run-docker-image:
    runs-on: self-hosted
    steps:
      - name: Set GitHub Environment variables
        run: |
          # Set GitHub Environment variables
          echo "DOCKER_IMAGE_NAME=${GITHUB_REPOSITORY}:latest" >> $GITHUB_ENV
          echo "DOCKER_CONTAINER_NAME=$(echo ${GITHUB_REPOSITORY} | cut -d'/' -f2)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          # Build Docker image
          docker build --platform linux/amd64 --tag ${{ env.DOCKER_IMAGE_NAME }} .

      - name: Run Docker image
        run: |
          # Run Docker image
          docker rm -f ${{ env.DOCKER_CONTAINER_NAME }}
          docker run --detach \
            --name ${{ env.DOCKER_CONTAINER_NAME }} \
            --publish 127.0.0.1:${{ secrets.STAGING_APP_PORT }}:${{ secrets.STAGING_APP_PORT }} \
            --env ASPNETCORE_ENVIRONMENT=Staging \
            --env ASPNETCORE_HTTP_PORTS=${{ secrets.STAGING_APP_PORT }} \
            --restart unless-stopped \
          ${{ env.DOCKER_IMAGE_NAME }}
